### ISSUE TITLE
undefined method `file'

### ISSUE THREAD

**Issue by m4rcu5** [Voxer/rcconf-cookbook#2]
Hi,

It seems that any implementation I try ends up in the following;

my code:
```
rcconf 'dhcpd_flags' do
  value '-q'
end
```

the error:
```
undefined method `file' for #<Chef::Provider::Rcconf:0x00000809a40360>
```

Any chance you can help me out here?

**Comment by anandsuresh** [comment]
What version of Chef are you using?

**Comment by m4rcu5** [comment]
Latest and greatest: Chef: 12.0.3

**Comment by m4rcu5** [comment]
With Chef 11.18.0 everything seems to be OK.

**Comment by anandsuresh** [comment]
This cookbook was tested primarily on chef 11.16.4. Quite possible that out
might break on chef 12.

Will look into it.

**Comment by bahamas10** [comment]
`Chef::Resource::File` was most likely `require`d automatically for library files in Chef 11 and removed in Chef 12.  I'll take a look in a bit as well... it may be as simple as requiring the necessary file.

Side note: I may rewrite this cookbook to simply be an LWRP to avoid weirdness like this in the future

**Comment by bahamas10** [comment]
@m4rcu5 can you try using the code from https://github.com/Voxer/rcconf-cookbook/pull/3 (branch dave-1422902076) to see if that works for you?

**Comment by m4rcu5** [comment]
Hi @bahamas10, I can confirm that your branch is working on Chef 12.0.3. Thx!

**Comment by bahamas10** [comment]
@m4rcu5 perfect! i'll merge it
